version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mailer
      MYSQL_ROOT_PASSWORD: 246808642aA@
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/static:/app/static
      - ./backend/media:/app/media
      - ./backend/logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DEBUG=1
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: ./backend
    command: celery -A config worker -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - web

  celery_beat:
    build: ./backend
    command: celery -A config beat -l INFO
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - web

volumes:
  mysql_data:
  redis:
  static_volume:
  media_volume:
  log_volume:
