global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics'
    scheme: http

  - job_name: 'celery'
    static_configs:
      - targets: ['celery_worker:8000']
    metrics_path: '/metrics' 