# Generated by Django 4.2.7 on 2024-12-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=255, null=True)),
                ('port', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('session', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, unique=True)),
                ('reason', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
                ('blocked_until', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP Blacklist',
                'verbose_name_plural': 'IP Blacklist',
                'db_table': 'ip_blacklist',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('session', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest', models.CharField(max_length=255, null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=255, null=True)),
                ('port', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='new', max_length=255, null=True)),
                ('session', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'smtp',
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempName', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('session', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintmp', models.IntegerField(null=True)),
                ('template', models.TextField(null=True)),
                ('froms', models.TextField(null=True)),
                ('subject', models.TextField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('session', models.CharField(max_length=255, null=True)),
                ('htmlbodies', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('data', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('session', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, null=True)),
                ('port', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='new', max_length=255, null=True)),
                ('session', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'proxy',
                'indexes': [models.Index(fields=['session', 'ip'], name='proxy_session_3b7f89_idx'), models.Index(fields=['status'], name='proxy_status_cf85bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('session', models.CharField(max_length=255, null=True)),
                ('tempName', models.CharField(max_length=255, null=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.template')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=255, null=True)),
                ('last', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('session', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='new', max_length=255, null=True)),
            ],
            options={
                'db_table': 'bases',
                'indexes': [models.Index(fields=['session', 'email'], name='bases_session_4318f1_idx'), models.Index(fields=['status'], name='bases_status_c41e09_idx')],
            },
        ),
    ]
