# Generated by Django 4.2.7 on 2024-12-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45, unique=True)),
                ('reason', models.TextField()),
                ('attempts', models.IntegerField(default=0)),
                ('blocked_until', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP Blacklist',
                'verbose_name_plural': 'IP Blacklist',
                'db_table': 'ip_blacklist',
            },
        ),
        migrations.AddField(
            model_name='base',
            name='status',
            field=models.CharField(default='new', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.CharField(default='new', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtp',
            name='status',
            field=models.CharField(default='new', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='base',
            index=models.Index(fields=['session', 'email'], name='bases_session_4318f1_idx'),
        ),
        migrations.AddIndex(
            model_name='base',
            index=models.Index(fields=['status'], name='bases_status_c41e09_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['session', 'ip'], name='proxy_session_3b7f89_idx'),
        ),
        migrations.AddIndex(
            model_name='proxy',
            index=models.Index(fields=['status'], name='proxy_status_cf85bb_idx'),
        ),
        migrations.AddIndex(
            model_name='smtp',
            index=models.Index(fields=['session', 'email'], name='smtp_session_78f5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='smtp',
            index=models.Index(fields=['status'], name='smtp_status_45fef6_idx'),
        ),
        migrations.AlterModelTable(
            name='base',
            table='bases',
        ),
        migrations.AlterModelTable(
            name='proxy',
            table='proxy',
        ),
        migrations.AlterModelTable(
            name='smtp',
            table='smtp',
        ),
    ]
