# Generated by Django 4.2.7 on 2024-12-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_ipblacklist_base_status_alter_proxy_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
