# Generated by Django 4.2.7 on 2024-12-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_remove_token_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smtp',
            name='smtp_session_78f5e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='smtp',
            name='smtp_status_45fef6_idx',
        ),
    ]
